apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: glgl2131/hello
      context: .
deploy:
  helm:
    releases:
      - name: hello-world
        chartPath: /home/vagrant/git-helm/hello-world
        # values:
          # images: glgl2131/hello