apiVersion: skaffold/v2alpha2
kind: Config
build:
  artifacts:
    - image: git-repo.asia-northeast3-a.c.lguplus-toy-project.internal/sample
      context: .
      docker:
        dockerfile: ./Dockerfile
deploy:
  helm:
    releases:
      - name: seongho-helm
        remote: true
        chartPath: http://34.64.189.226:8080/charts/example-helm-0.1.0.tgz
        values:
          image: git-repo.asia-northeast3-a.c.lguplus-toy-project.internal/sample
    flags:
      upgrade:
        - --install