apiVersion: skaffold/v2alpha2
kind: Config
build:
  artifacts:
    - image: glgl2131/helm-test
      context: .
deploy:
  helm:
    releases:
      - name: seongho-helm-test02
        remote: true
        chartPath: https://qkrtjddlsgh.github.io/helm-chart-repo/stable/hello-world-0.1.0.tgz
        values:
          images: glgl2131/helm-test
  kubeContext: gke_sunlit-apricot-177815_asia-northeast1-a_seongho-k8s-cluster