apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: glgl2131/hello
      context: .
deploy:
  helm:
    releases:
      - name: seongho-test01
        chartPath: /home/vagrant/git-helm
        values:
          images: glgl2131/hello