apiVersion: skaffold/v2alpha2
kind: Config
build:
  artifacts:
    - image: lgcns.registry.com/k8s-sample
      context: .
      docker:
        dockerfile: ./Dockerfile
deploy:
  helm:
    releases:
      - name: seongho-helm
        remote: true
        chartPath: http://10.94.24.188:8080/charts/example-helm-0.1.0.tgz
        values:
          image: lgcns.registry.com/k8s-sample
    flags:
      upgrade:
        - --install