apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: glgl2131/hello
      context: .
deploy:
  kubectl:
    manifests:
    - https://raw.githubusercontent.com/qkrtjddlsgh/ansible_playbook/master/skaffold_deployment.yaml